version: "3"

services:
  web:
    image: re-cipes:latest
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - "./backend/app.db:/app/app.db:rw"
      - "./backend/app:/app/app:ro"
  static:
    image: nginx
    volumes:
      - "./static/:/usr/share/nginx/html/static/:ro"
    ports:
      - "8080:80"

